### ISSUE TITLE
Using 4-dimensional data with DeepLab

### ISSUE THREAD

**Issue by gmvincent** [yassouali/pytorch-segmentation#120]
I am trying to create a data loader for a custom data set where each image has a shape of [time-points, height, width, features (9)]. After following the provided data loaders within this repository, I get a value error where it appears that the data is not being passed through the data loader probably. Do you have any suggestions for how to get a 4D numpy array through the data loaders?

```
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 22, in main
    train_loader = get_instance(dataloaders, 'train_loader', config)
  File "train.py", line 16, in get_instance
    return getattr(module, config[name]['type'])(*args, config[name]['args'])
  File "/home/ncouch/NRL Pipeline/pytorch-segmentation/dataloaders/sentinelhub.py", line 93, in init
    super(SH, self).init(self.dataset, batch_size, shuffle, num_workers, val_split)
  File "/home/ncouch/NRL Pipeline/pytorch-segmentation/base/base_dataloader.py", line 22, in init
    super(BaseDataLoader, self).init(sampler=self.train_sampler, self.init_kwargs)
  File "/cm/shared/apps/pytorch-py37-cuda10.2-gcc8/1.7.1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 262, in init
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/cm/shared/apps/pytorch-py37-cuda10.2-gcc8/1.7.1/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 104, in init
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

[sh_dataloader.txt](https://github.com/yassouali/pytorch-segmentation/files/6894738/sh_dataloader.txt)

**Comment by yassouali** [comment]
Hi @gmvincent 

You can either:
1) Go through the model, convert each module into 3D version by copying it over time and dividing by the temporal size (see this paper; https://arxiv.org/abs/1705.07750) However, in this case better to just find a 3D model.

2) which is easier, simply reshape your inputs into TxN, H, W, then at the outputs, reshape back into T, C, H, W and compute the loss if you have a label per temporal dimension, if not average across the temporal dimension and compute the loss.

Good luck
