### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

### ISSUE THREAD

**Issue by Shk-aftab** [yassouali/pytorch-segmentation#141]
Detected GPUs: 1 Requested: 1

  0%|                                                                                                    | 0/4331 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "train.py", line 62, in <module>
    main(config, args.resume)
  File "train.py", line 43, in main
    trainer.train()
  File "/home/mobility/workspace/pytorch-segmentation/base/base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "/home/mobility/workspace/pytorch-segmentation/trainer.py", line 60, in _train_epoch
    output = self.model(data)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mobility/workspace/pytorch-segmentation/models/pspnet.py", line 79, in forward
    x = self.initial(x)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mobility/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

**Comment by yassouali** [comment]
Hi @Shk-aftab 

I think this has to do more with the env rather than the code; maybe try seeing previous posts about the same problem like this [one](https://discuss.pytorch.org/t/a-error-when-using-gpu/32761)
